version: '3'

services:
  local-ultimate-hello-world-cra:
    image: node:17
    volumes:
      - ./:/app
    environment:
        - DB_URI=mongodb://ultimate-hello-world-cra-user:ultimate-hello-world-cra-pass@local-mongo:27017
        - DB_NAMESPACE=ultimateHelloWorldCra
    ports:
      - '3000:3000'
      - '3001:3001'
      - '9229:9229'
    tty: true
    working_dir: /app
    command: bash /app/docker-entrypoint.sh

  local-mongo:
    image: mongo:5.0.3
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    tty: true
    volumes:
      - local-ultimate-hello-world-cra-data:/data/db
      - ./mongodb:/docker-entrypoint-initdb.d:ro

volumes:
  local-ultimate-hello-world-cra-data: