version: '2.4'

services:
  ultimate-hello-world-cra-web:
    image: ${APP_IMAGE}
    environment:
        - DB_URI=mongodb://ultimate-hello-world-cra-user:ultimate-hello-world-cra-pass@mongo:27017
        - DB_NAMESPACE=ultimateHelloWorldCra
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    tty: true

  cypress:
    build: ./
    environment:
      - CYPRESS_baseUrl=http://ultimate-hello-world-cra-web:3000
    depends_on:
      - ultimate-hello-world-cra-web

  mongo:
    build:
      context: ../mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: admin
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    tty: true